# Generated by Django 2.1.1 on 2021-08-17 05:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('executionEnvironment', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='TestRunPending', max_length=20)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('via', django.contrib.postgres.fields.jsonb.JSONField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'db_table': 'testsuites',
            },
        ),
    ]
