# Generated by Django 2.1.1 on 2021-08-17 05:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('vias', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), size=None)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
                ('tests', models.ManyToManyField(to='testcases.TestCase')),
            ],
            options={
                'db_table': 'hooks',
            },
        ),
    ]
