# Generated by Django 2.1.1 on 2021-08-17 05:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('generator', django.contrib.postgres.fields.jsonb.JSONField()),
                ('variables', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'db_table': 'setups',
            },
        ),
        migrations.CreateModel(
            name='SetupAndTestCaseIntermediateTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(blank=True, null=True)),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steps.Setup')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.TestCase')),
            ],
            options={
                'db_table': 'setups_testcases',
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('step_number'), nulls_last=True)],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teardown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('generator', django.contrib.postgres.fields.jsonb.JSONField()),
                ('variables', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'db_table': 'teardowns',
            },
        ),
        migrations.CreateModel(
            name='TeardownAndTestCaseIntermediateTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(blank=True, null=True)),
                ('teardown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steps.Teardown')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.TestCase')),
            ],
            options={
                'db_table': 'teardowns_testcases',
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('step_number'), nulls_last=True)],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='teardown',
            name='tests',
            field=models.ManyToManyField(through='steps.TeardownAndTestCaseIntermediateTable', to='testcases.TestCase'),
        ),
        migrations.AddField(
            model_name='setup',
            name='tests',
            field=models.ManyToManyField(through='steps.SetupAndTestCaseIntermediateTable', to='testcases.TestCase'),
        ),
        migrations.AlterUniqueTogether(
            name='teardownandtestcaseintermediatetable',
            unique_together={('testcase', 'teardown')},
        ),
        migrations.AlterUniqueTogether(
            name='setupandtestcaseintermediatetable',
            unique_together={('testcase', 'setup')},
        ),
    ]
